source("/home/yi/Dropbox/SocialFitnessEffects/Code/load.r")
pdf("Figures/Figure_S1_S.pdf", height= 5, width=6)
load("Results/Selection.RData")
par(mfrow=c(2,1), mar=c(4,4,2,1))
plot(NA, ylim=c(0,400), xlim=c(0,200), ylab="Population size", xlab="Time steps")
#plot_n(s1a, "black")  
plot_n(s1b, "blue")  
plot_n(s1c, "orange")  
plot_n(s1d, "darkgreen")  

plot(NA, ylim=c(0,15), xlim=c(0,200), ylab="Mean phenotype", xlab="Time steps")
#plot_z(s1a, "black")  
plot_z(s1b, "blue")  
plot_z(s1c, "orange")  
plot_z(s1d, "darkgreen")  

dev.off()

pdf("Figures/Figure_S1_DDS.pdf", height= 5, width=6)
load("Results/DensityDependentSelection.RData")
par(mfrow=c(2,1), mar=c(4,4,2,1))
plot(NA, ylim=c(0,600), xlim=c(0,300), ylab="Population size", xlab="Time steps")
#plot_n(s1a, "black")  
plot_n(s2b, "blue")  
plot_n(s2c, "orange")  
plot_n(s2d, "darkgreen")  

plot(NA, ylim=c(0,15), xlim=c(0,300), ylab="Mean phenotype", xlab="Time steps")
#plot_z(s1a, "black")  
plot_z(s2b, "blue")  
plot_z(s2c, "orange")  
plot_z(s2d, "darkgreen")  

dev.off()


pdf("Figures/Figure_S1_FD.pdf", height= 8, width=6)
load("Results/FrequencyDependence.RData")
par(mfrow=c(2,1), mar=c(4,4,2,1))
plot(NA, ylim=c(0,150), xlim=c(0,200), ylab="Population size", xlab="Time steps")
#plot_n(s1a, "black")  
plot_n(s3b, "blue")  
plot_n(s3c, "orange")  
plot_n(s3d, "darkgreen")  

plot(NA, ylim=c(-7,7), xlim=c(0,200), ylab="Mean phenotype", xlab="Time steps")
#plot_z(s1a, "black")  
plot_z(s3b, "blue")  
plot_z(s3c, "orange")  
plot_z(s3d, "darkgreen")  
dev.off()

load("Results/FrequencyDependentSelection.RData")
pdf("Figures/Figure_S1_FDS.pdf", height= 7, width=5)
par(mfrow=c(2,1), mar=c(4,4,2,1))
plot(NA, ylim=c(0,400), xlim=c(0,200), ylab="Population size", xlab="Time steps")
#plot_n(s1a, "black")  
plot_n(s4b, "blue")  
plot_n(s4c, "orange")  
plot_n(s4d, "darkgreen")  

plot(NA, ylim=c(0,15), xlim=c(0,200), ylab="Mean phenotype", xlab="Time steps")
#plot_z(s1a, "black")  
plot_z(s4b, "blue")  
plot_z(s4c, "orange")  
plot_z(s4d, "darkgreen")  
dev.off()

load("Results/FrequencyDensityDependentSelection.RData")
pdf("Figures/Figure_S1_FDDS.pdf", height= 7, width=5)
par(mfrow=c(2,1), mar=c(4,4,2,1))
plot(NA, ylim=c(0,400), xlim=c(0,200), ylab="Population size", xlab="Time steps")
#plot_n(s1a, "black")  
plot_n(s5b, "blue")  
plot_n(s5c, "orange")  
plot_n(s5d, "darkgreen")  

plot(NA, ylim=c(0,15), xlim=c(0,200), ylab="Mean phenotype", xlab="Time steps")
#plot_z(s1a, "black")  
plot_z(s5b, "blue")  
plot_z(s5c, "orange")  
plot_z(s5d, "darkgreen")  
dev.off()

